=== agnieszka2018/xml_schema/xmlSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:ksi="http://www.example.org/ksiegarnia"
           targetNamespace="http://www.example.org/ksiegarnia"            
           elementFormDefault="qualified">
    
    <!-- Adnotacja -->   
    <xs:annotation>
        <xs:documentation>
            Zadanie 2, dokument XML Schema.
        </xs:documentation>
    </xs:annotation>
    
    <!-- Key, Keyref -->    
    <xs:element name="księgarnia" type="ksi:księgarniaType">
        <xs:key name="idDziałKey">
            <xs:selector xpath="ksi:dział"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:key name="autorIdKey">
            <xs:selector xpath="ksi:autor"/>
            <xs:field xpath="@autorId"/>
        </xs:key>
        <xs:keyref name="książkaRefKey" refer="ksi:autorIdKey">
            <xs:selector xpath="ksi:książka"/>
            <xs:field xpath="@książkaAutorId"/>
        </xs:keyref> 
        <xs:key name="książkaIdKey">
            <xs:selector xpath="ksi:książka"/>
            <xs:field xpath="@id"/>
        </xs:key>
    </xs:element>
    
    <!-- Typy danych -->  
    <xs:complexType name="księgarniaType">
        <xs:sequence>
            <xs:element name="info" type="ksi:infoType" maxOccurs="1"/>
            <xs:element name="tytułStrony" type="ksi:tytułStronyType" maxOccurs="1"/>   
            <xs:element name="modyfikacja" type="ksi:modyfikacjaType" maxOccurs="1"/>
            <xs:element name="dział" type="ksi:działType" maxOccurs="unbounded"/>                      
        </xs:sequence>      
    </xs:complexType> 
           
    <xs:simpleType name="infoType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
            <xs:maxLength value="100" />
        </xs:restriction>
    </xs:simpleType> 
    
    <xs:simpleType name="tytułStronyType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
            <xs:maxLength value="100" />
        </xs:restriction>
    </xs:simpleType> 
    
    <xs:complexType name="modyfikacjaType" mixed="true">    
        <xs:sequence>
            <xs:element name="ukryta_wiadomość" type="ksi:ukryta_wiadomośćType" maxOccurs="1"/> 
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="ukryta_wiadomośćType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
            <xs:maxLength value="100" />
        </xs:restriction>
    </xs:simpleType> 
        
    <xs:complexType name="działType">
        <xs:sequence>
            <xs:element name="nazwa" type="ksi:nazwaType" maxOccurs="1"/>
            <xs:element name="autor" type="ksi:autorType" maxOccurs="unbounded"/>                           
        </xs:sequence>             
        <xs:attribute name="id" type="xs:string" use="required" />           
    </xs:complexType> 
    
    <xs:complexType name="nazwaType" mixed="true">    
        <xs:sequence>
            <xs:element name="wiadomość" type="ksi:wiadomośćType" maxOccurs="1"/> 
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="wiadomośćType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
            <xs:maxLength value="500" />
        </xs:restriction>
    </xs:simpleType> 
    
    <xs:complexType name="autorType" mixed="true">    
        <xs:sequence>
            <xs:element name="książka" type="ksi:książkaType" maxOccurs="unbounded"/> 
        </xs:sequence>
        <xs:attribute name="autorId" type="xs:string" use="required" />    
    </xs:complexType>
    
    
    <xs:complexType name="książkaType">
        <xs:group ref="ksi:książkaElements"/>
        <xs:attributeGroup ref="ksi:książkaAttr"/>
    </xs:complexType>
    
    <xs:simpleType name="tytułType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
            <xs:maxLength value="500" />
        </xs:restriction>
    </xs:simpleType> 
    
    <xs:simpleType name="opisType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
            <xs:maxLength value="5000" />
        </xs:restriction>
    </xs:simpleType> 

    <xs:simpleType name="stronType">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0-9]{0,5}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="cenaType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="ksi:waluta"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:simpleType name ="walutaAttr">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PLN" />
            <xs:enumeration value="EUR" />
            <xs:enumeration value="DOL" />
        </xs:restriction>
    </xs:simpleType>  
    
    <!-- Grupa elementów -->   
    <xs:group name="książkaElements">
        <xs:sequence>            
            <xs:element name="tytuł" type="ksi:tytułType" /> 
            <xs:element name="opis" type="ksi:opisType" /> 
            <xs:element name="dataPublikacji" type="xs:date" /> 
            <xs:element name="stron" type="ksi:stronType" />
            <xs:element name="cena" type="ksi:cenaType" />             
        </xs:sequence>
    </xs:group>
    
    <!-- Grupa atrybutów --> 
    <xs:attributeGroup name="książkaAttr">
        <xs:attribute name="książkaAutorId" type="xs:string" use="required"/>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:attributeGroup>
    
    <xs:attribute name="waluta" type="ksi:walutaAttr"/> 
    
</xs:schema>

=== agnieszka2018/xml_schema/ksiegarnia.xml
<?xml version="1.0" encoding="UTF-8" ?>

<ksi:księgarnia xmlns:ksi="http://www.example.org/ksiegarnia" 
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                xsi:schemaLocation="http://www.example.org/ksiegarnia xmlSchema.xsd">

    <ksi:info>
        Autorzy 
    </ksi:info>
    <ksi:tytułStrony>
        &quot;KSIĘGARNIA&quot;
    </ksi:tytułStrony>

    <ksi:modyfikacja>Najedź, aby sprawdzić datę ostatniej modyfikacji!<ksi:ukryta_wiadomość>Ostatnia modyfikacja: 2018-10-23</ksi:ukryta_wiadomość></ksi:modyfikacja>

    <ksi:dział id="fantastyka"> 
        <ksi:nazwa>
            Fantastyka
            <ksi:wiadomość>
                Fantastyka – gatunek literacki, a także filmowy, komiksowy, gier a niekiedy i malarstwa. Polega ona na kreowaniu świata przedstawionego, 
                który w całości, lub w części różni się od rzeczywistości, na przykład przez dodanie elementów nadnaturalnych, lub stworzonej przez ksi:autora technologii.
            </ksi:wiadomość>
        </ksi:nazwa>
        <ksi:autor autorId="AS"> Andrzej Sapkowski
            <ksi:książka książkaAutorId="AS" id="pierwsza">
                <ksi:tytuł>Miecz przeznaczenia</ksi:tytuł>
                <ksi:opis>Wiedźmiński kodeks stawia tę sprawę w sposób jednoznaczny: wiedźminowi smoka zabijać się nie godzi. To gatunek zagrożony wymarciem. 
                    Aczkolwiek w powszechnej opinii to gad najbardziej wredny. Na oszluzgi, widłogony i latawce kodeks polować przyzwala. Ale na smoki – nie. </ksi:opis>
                <ksi:dataPublikacji>1980-08-21</ksi:dataPublikacji>
                <ksi:stron>250</ksi:stron>
                <ksi:cena ksi:waluta="PLN">30</ksi:cena>
            </ksi:książka>
            <ksi:książka książkaAutorId="AS" id="druga">
                <ksi:tytuł>Ostatnie życzenie</ksi:tytuł>
                <ksi:opis>Później mówiono, że człowiek ów nadszedł od północy, od Bramy Powroźniczej. Nie był stary, ale włosy miał zupełnie białe. Kiedy ściągnął 
                    płaszcz, okazało się, że na pasie za plecami ma miecz. Białowłosego przywiodło do miasta królewskie orędzie: trzy tysiące orenów nagrody 
                    za odczarowanie nękającej mieszkańców Wyzimy strzygi. Takie czasy nastały. </ksi:opis>
                <ksi:dataPublikacji>1980-08-21</ksi:dataPublikacji>
                <ksi:stron>250</ksi:stron>
                <ksi:cena ksi:waluta="PLN">30</ksi:cena>
            </ksi:książka>
        </ksi:autor>
        <ksi:autor autorId="DG"> Dmitrij Głuchowski
            <ksi:książka książkaAutorId="DG" id="trzecia">
                <ksi:tytuł> Metro 2033</ksi:tytuł>
                <ksi:opis>Rok 2033. Świat po zagładzie nuklearnej. Ocalali walczą o przetrwanie w sieci moskiewskiego metra. Ich los trafia w ręce młodego Artema.</ksi:opis>
                <ksi:dataPublikacji>1980-08-21</ksi:dataPublikacji>
                <ksi:stron>250</ksi:stron>
                <ksi:cena ksi:waluta="PLN">30</ksi:cena>
            </ksi:książka>
        </ksi:autor>
    </ksi:dział>
    <ksi:dział id="literatura_współczesna"> 
        <ksi:nazwa>
            Literatura współczesna
            <ksi:wiadomość>
                Literatura współczesna - nazwa ta obejmuje ostatni okres literacki, trwający od wybuchu II wojny światowej we wrześniu 1939 r. do dnia dzisiejszego – jest to więc epoka niezamknięta; 
                jej materiał literacki i krytyczny narasta. 
            </ksi:wiadomość>
        </ksi:nazwa>
        <ksi:autor autorId="DT"> Donna Tartt
            <ksi:książka książkaAutorId="DT" id="czwarta">
                <ksi:tytuł>Szczygieł</ksi:tytuł>
                <ksi:opis>Szczygieł, pilnie strzeżony symbol bezpowrotnie utraconego życia, będzie towarzyszył Theo w 
                    nieustającej podróży: od ekskluzywnych apartamentów przy Park Avenue po rozpustę półświatka w Las Vegas.</ksi:opis>
                <ksi:dataPublikacji>2015-05-06</ksi:dataPublikacji>
                <ksi:stron>784</ksi:stron>
                <ksi:cena ksi:waluta="PLN">48,99</ksi:cena>
            </ksi:książka>
            <ksi:książka książkaAutorId="DT" id="piąta">
                <ksi:tytuł>Tajemna historia</ksi:tytuł>
                <ksi:opis>Richard Papen rozpoczyna naukę w ekskluzywnym college’u w Nowej Anglii. Dołącza do grupy inteligentnych, ekscentrycznych
                    studentów filologii klasycznej, którzy pod wodzą charyzmatycznego wykładowcy odkrywają sposób myślenia i życia niemający 
                    nic wspólnego z monotonną egzystencją ich rówieśników.</ksi:opis>
                <ksi:dataPublikacji>2017-09-20</ksi:dataPublikacji>
                <ksi:stron>608</ksi:stron>
                <ksi:cena ksi:waluta="PLN">37,99</ksi:cena>
            </ksi:książka>
        </ksi:autor>
        <ksi:autor autorId="JDS"> J. D. Salinger
            <ksi:książka książkaAutorId="JDS" id="szósta">
                <ksi:tytuł>Buszujący w zbożu</ksi:tytuł>
                <ksi:opis>Bohaterem 'Buszującego w zbożu' jest szesnastoletni uczeń, Holden Caulfield, który nie mogąc pogodzić się z otaczającą go 
                    głupotą, podłością, a przede wszystkim zakłamaniem, ucieka z college`u i przez kilka dni 'buszuje' po Nowym Jorku, nim wreszcie 
                    powróci do domu rodzinnego.</ksi:opis>
                <ksi:dataPublikacji>1951-07-16</ksi:dataPublikacji>
                <ksi:stron>277</ksi:stron>
                <ksi:cena ksi:waluta="PLN">11,99</ksi:cena>
            </ksi:książka>
        </ksi:autor>
        <ksi:autor autorId="NHL"> N. Harper Lee
            <ksi:książka książkaAutorId="NHL" id="siódma">
                <ksi:tytuł>Zabić drozda</ksi:tytuł>
                <ksi:opis>Lata trzydzieste XX wieku, małe miasteczko na południu USA. Atticus Finch, adwokat i głowa rodziny, broni młodego Murzyna oskarżonego 
                    o zgwałcenie biednej białej dziewczyny Mayelli Ewell. Prosta sprawa sądowa z powodu wszechpanującego rasizmu, urasta do rangi symbolu.</ksi:opis>
                <ksi:dataPublikacji>2015-10-20</ksi:dataPublikacji>
                <ksi:stron>424</ksi:stron>
                <ksi:cena ksi:waluta="PLN">22,80</ksi:cena>
            </ksi:książka>
            <ksi:książka książkaAutorId="NHL" id="ósma">
                <ksi:tytuł>Idź, postaw wartownika</ksi:tytuł>
                <ksi:opis>Maycomb, Alabama. Dwudziestosześcioletnia Jean Louise Finch, zwana Skautem, powraca z Nowego Jorku w rodzinne ksi:strony, do starzejącego się ojca. 
                    Na południu Stanów Zjednoczonych panuje zamęt polityczny;</ksi:opis>
                <ksi:dataPublikacji>2015-11-04</ksi:dataPublikacji>
                <ksi:stron>368</ksi:stron>
                <ksi:cena ksi:waluta="PLN">30,72</ksi:cena>
            </ksi:książka>
        </ksi:autor>
    </ksi:dział>
    <ksi:dział id="kryminał">
        <ksi:nazwa>
            Kryminał
            <ksi:wiadomość>
                Powieść kryminalna – odmiana powieści charakteryzująca się fabułą zorganizowaną wokół zbrodni, okoliczności dojścia do niej, dochodzenia oraz ujawnienia osoby sprawcy.
            </ksi:wiadomość>
        </ksi:nazwa>
        <ksi:autor autorId="SK"> Stephen King
            <ksi:książka książkaAutorId="SK" id="dziewiąta">
                <ksi:tytuł>Zielona Mila</ksi:tytuł>
                <ksi:opis>Akcja powieści, zbliżonej klimatem do głośnej noweli tego samego autora, toczy się w Ameryce lat 30. Jej bohaterowie to więźniowie oczekujący na 
                    wykonanie kary śmierci i pilnujący ich strażnicy.</ksi:opis>
                <ksi:dataPublikacji>2017-05-31</ksi:dataPublikacji>
                <ksi:stron>416</ksi:stron>
                <ksi:cena ksi:waluta="PLN">12,98</ksi:cena>
            </ksi:książka>        
            <ksi:książka książkaAutorId="SK" id="dziesiąta">
                <ksi:tytuł>Lśnienie</ksi:tytuł>
                <ksi:opis>To jeden z najlepszych współczesnych horrorów. Nastrój grozy i napięcia potęguje się w niej z każdą minutą. Pięcioletni chłopiec Danny znala 
                    się z rodzicami w opustoszałym na zimie hotelu. Wrażliwe, obdarzone zdolnościami wizjonerskimi dziecko odbiera fluidy czające się w jego murach;</ksi:opis>
                <ksi:dataPublikacji>2009-10-13</ksi:dataPublikacji>
                <ksi:stron>520</ksi:stron>
                <ksi:cena ksi:waluta="PLN">30,49</ksi:cena>
            </ksi:książka>     
            <ksi:książka książkaAutorId="SK" id="jedenasta">
                <ksi:tytuł>Bastion</ksi:tytuł>
                <ksi:opis>Najdłuższa i według powszechnych ocen najlepsza powieść w dorobku Stephena Kinga – apokaliptyczny thriller mistrza grozy.</ksi:opis>
                <ksi:dataPublikacji>2018-09-19</ksi:dataPublikacji>
                <ksi:stron>1166</ksi:stron>
                <ksi:cena ksi:waluta="PLN">39,49</ksi:cena>
            </ksi:książka>                
        </ksi:autor> 
        <ksi:autor autorId="RM"> Remigiusz Mróz
            <ksi:książka książkaAutorId="RM" id="dwunasta">
                <ksi:tytuł>Kontratyp</ksi:tytuł>
                <ksi:opis>W drodze na Annapurnę, jeden z najgroźniejszych szczytów na świecie, ginie troje polskich wspinaczy. Ekipy ratunkowe odnajdują 
                    jedynie przysypane śniegiem, poskręcane liny, ale nie trafiają na żaden inny ślad po grupie.</ksi:opis>
                <ksi:dataPublikacji>2018-09-19</ksi:dataPublikacji>
                <ksi:stron>532</ksi:stron>
                <ksi:cena ksi:waluta="PLN">29,93</ksi:cena>
            </ksi:książka>            
        </ksi:autor>       
    </ksi:dział>
    <ksi:dział id="klasyka">
        <ksi:nazwa>
            Klasyka
            <ksi:wiadomość>
